// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModelInput struct {
	Features             []float64 `protobuf:"fixed64,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ModelInput) Reset()         { *m = ModelInput{} }
func (m *ModelInput) String() string { return proto.CompactTextString(m) }
func (*ModelInput) ProtoMessage()    {}
func (*ModelInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ModelInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelInput.Unmarshal(m, b)
}
func (m *ModelInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelInput.Marshal(b, m, deterministic)
}
func (m *ModelInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelInput.Merge(m, src)
}
func (m *ModelInput) XXX_Size() int {
	return xxx_messageInfo_ModelInput.Size(m)
}
func (m *ModelInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelInput.DiscardUnknown(m)
}

var xxx_messageInfo_ModelInput proto.InternalMessageInfo

func (m *ModelInput) GetFeatures() []float64 {
	if m != nil {
		return m.Features
	}
	return nil
}

type ModelOutput struct {
	Label                int64    `protobuf:"varint,1,opt,name=label,proto3" json:"label,omitempty"`
	Probability          float64  `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelOutput) Reset()         { *m = ModelOutput{} }
func (m *ModelOutput) String() string { return proto.CompactTextString(m) }
func (*ModelOutput) ProtoMessage()    {}
func (*ModelOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ModelOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelOutput.Unmarshal(m, b)
}
func (m *ModelOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelOutput.Marshal(b, m, deterministic)
}
func (m *ModelOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelOutput.Merge(m, src)
}
func (m *ModelOutput) XXX_Size() int {
	return xxx_messageInfo_ModelOutput.Size(m)
}
func (m *ModelOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ModelOutput proto.InternalMessageInfo

func (m *ModelOutput) GetLabel() int64 {
	if m != nil {
		return m.Label
	}
	return 0
}

func (m *ModelOutput) GetProbability() float64 {
	if m != nil {
		return m.Probability
	}
	return 0
}

func init() {
	proto.RegisterType((*ModelInput)(nil), "server.ModelInput")
	proto.RegisterType((*ModelOutput)(nil), "server.ModelOutput")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x71, 0x53, 0x8b, 0x94,
	0x34, 0xb8, 0xb8, 0x7c, 0xf3, 0x53, 0x52, 0x73, 0x3c, 0xf3, 0x0a, 0x4a, 0x4b, 0x84, 0xa4, 0xb8,
	0x38, 0xd2, 0x52, 0x13, 0x4b, 0x4a, 0x8b, 0x52, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35, 0x18, 0x83,
	0xe0, 0x7c, 0x25, 0x57, 0x2e, 0x6e, 0xb0, 0x4a, 0xff, 0xd2, 0x12, 0x90, 0x52, 0x11, 0x2e, 0xd6,
	0x9c, 0xc4, 0xa4, 0xd4, 0x1c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x08, 0x47, 0x48, 0x81,
	0x8b, 0xbb, 0xa0, 0x28, 0x3f, 0x29, 0x31, 0x29, 0x33, 0x27, 0xb3, 0xa4, 0x52, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x31, 0x08, 0x59, 0xc8, 0xc8, 0x96, 0x8b, 0x15, 0x6c, 0x8c, 0x90, 0x09, 0x17, 0xbb,
	0x5b, 0x7e, 0x51, 0x79, 0x62, 0x51, 0x8a, 0x90, 0x90, 0x1e, 0xc4, 0x35, 0x7a, 0x08, 0xa7, 0x48,
	0x09, 0xa3, 0x88, 0x41, 0x2c, 0x55, 0x62, 0x70, 0xe2, 0x88, 0x82, 0xba, 0x3c, 0x89, 0x0d, 0xec,
	0x11, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x32, 0x10, 0x87, 0xd9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModelClient is the client API for Model service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelClient interface {
	Forward(ctx context.Context, in *ModelInput, opts ...grpc.CallOption) (*ModelOutput, error)
}

type modelClient struct {
	cc *grpc.ClientConn
}

func NewModelClient(cc *grpc.ClientConn) ModelClient {
	return &modelClient{cc}
}

func (c *modelClient) Forward(ctx context.Context, in *ModelInput, opts ...grpc.CallOption) (*ModelOutput, error) {
	out := new(ModelOutput)
	err := c.cc.Invoke(ctx, "/server.Model/Forward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServer is the server API for Model service.
type ModelServer interface {
	Forward(context.Context, *ModelInput) (*ModelOutput, error)
}

func RegisterModelServer(s *grpc.Server, srv ModelServer) {
	s.RegisterService(&_Model_serviceDesc, srv)
}

func _Model_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Model/Forward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).Forward(ctx, req.(*ModelInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Model_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Model",
	HandlerType: (*ModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _Model_Forward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
