# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='server',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\x12\x06server\"\x1e\n\nModelInput\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x01\"1\n\x0bModelOutput\x12\r\n\x05label\x18\x01 \x01(\x03\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x32=\n\x05Model\x12\x34\n\x07\x46orward\x12\x12.server.ModelInput\x1a\x13.server.ModelOutput\"\x00\x42\x08Z\x06serverb\x06proto3')
)




_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='server.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='server.ModelInput.features', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=55,
)


_MODELOUTPUT = _descriptor.Descriptor(
  name='ModelOutput',
  full_name='server.ModelOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='server.ModelOutput.label', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probability', full_name='server.ModelOutput.probability', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
DESCRIPTOR.message_types_by_name['ModelOutput'] = _MODELOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), dict(
  DESCRIPTOR = _MODELINPUT,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:server.ModelInput)
  ))
_sym_db.RegisterMessage(ModelInput)

ModelOutput = _reflection.GeneratedProtocolMessageType('ModelOutput', (_message.Message,), dict(
  DESCRIPTOR = _MODELOUTPUT,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:server.ModelOutput)
  ))
_sym_db.RegisterMessage(ModelOutput)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006server'))

_MODEL = _descriptor.ServiceDescriptor(
  name='Model',
  full_name='server.Model',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=108,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='Forward',
    full_name='server.Model.Forward',
    index=0,
    containing_service=None,
    input_type=_MODELINPUT,
    output_type=_MODELOUTPUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['Model'] = _MODEL

# @@protoc_insertion_point(module_scope)
